### ISSUE TITLE
Icingaweb2 - AttributeError: 'NonType' object has no attribute 'get' 

### ISSUE THREAD

**Issue by laberator** [HenriWahl/Nagstamon#461]
Hi,

I'm experiencing "AttributeError: 'NonType' object has no attribute 'get' " error when connecting to an Icingaweb2 monitoring server (from Windows x64 Nagstamon binary). I'm unable to see anything else besides this error message. It works on 3.0 from my colleagues computer, but not in latest stable or dev. release.

![image](https://user-images.githubusercontent.com/31061470/32892655-45c3246a-cad7-11e7-8201-23da9ef887e2.png)

Client OS: Windows 10 1709 update
Monitoring server: Icinga2 (r2.7.0-1)
Icingaweb2: 2.4.1

**Comment by HenriWahl** [comment]
Can you run Nagstamon from source in a console window? If not on your own, use the version from https://seafile.ifw-dresden.de/f/67cb7de276bd4c26908c/ which brings all requirements to get some useful console output when running on Windows.

**Comment by HenriWahl** [comment]
By the way - did you have the problems with older Windows 10 version too?

**Comment by laberator** [comment]
I did not have this problem before the update. Although it has worked before on the creators fall update 1709 (but not on this newly installed machine). I'll get back to you next week, regarding the console output.

**Comment by laberator** [comment]
Here's the console output:

`QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
DEBUG: 2017-11-20 08:05:57.619691 Monitor server Created server.
Traceback (most recent call last):
  File "C:\Users\tomlab\Downloads\Nagstamon_debug\Nagstamon\Nagstamon\Servers\Generic.py", line 1431, in FetchURL
    yummysoup = BeautifulSoup(response.text, self.PARSER)
  File "C:\Users\tomlab\Downloads\Nagstamon_debug\python36\lib\site-packages\bs4\__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
DEBUG: Initializing SystemTrayIcon
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001B8ADF96AF8> for state "OK"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001B8ADF96A68> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001B8ADF96B88> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001B8ADF96C18> for state "WARNING"
Traceback (most recent call last):
  File "C:\Users\tomlab\Downloads\Nagstamon_debug\Nagstamon\Nagstamon\Servers\Generic.py", line 1373, in FetchURL
    response = self.session.get(url, timeout=self.timeout)
AttributeError: 'NoneType' object has no attribute 'get'
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001B8ADF96CA8> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001B8ADF96D38> for state "HIGH"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001B8ADF96DC8> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001B8ADF96E58> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001B8ADF96EE8> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001B8ADF96F78> for state "DOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x000001B8AEBA5048> for state "ERROR"
DEBUG: SystemTrayIcon initial icon: <PyQt5.QtGui.QIcon object at 0x000001B8AEBA5168>
DEBUG: 2017-11-20 08:05:58.600195 Monitor server FetchURL: http://172.30.0.12/icingaweb2/authentication/login CGI Data: None
ERROR: 2017-11-20 08:05:58.988213 Monitor server Traceback (most recent call last):
  File "C:\Users\tomlab\Downloads\Nagstamon_debug\Nagstamon\Nagstamon\Servers\Generic.py", line 1431, in FetchURL
    yummysoup = BeautifulSoup(response.text, self.PARSER)
  File "C:\Users\tomlab\Downloads\Nagstamon_debug\python36\lib\site-packages\bs4\__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

DEBUG: 2017-11-20 08:05:58.988213 Monitor server FetchURL: http://172.30.0.12/icingaweb2/monitoring/list/hosts?host_state>0&host_state<=2&host_state_type=1&addColumns=host_last_check&format=json CGI Data: None
DEBUG: 2017-11-20 08:05:59.119559 Monitor server FetchURL: http://172.30.0.12/icingaweb2/monitoring/list/hosts?host_state>0&host_state<=2&host_state_type=1&addColumns=host_last_check&format=json CGI Data: None
ERROR: 2017-11-20 08:05:59.193754 Monitor server Traceback (most recent call last):
  File "C:\Users\tomlab\Downloads\Nagstamon_debug\Nagstamon\Nagstamon\Servers\Generic.py", line 1373, in FetchURL
    response = self.session.get(url, timeout=self.timeout)
AttributeError: 'NoneType' object has no attribute 'get'

DEBUG: 2017-11-20 08:06:00.865909 Monitor server FetchURL: https://nagstamon.ifw-dresden.de/version/unstable CGI Data: None
C:\Users\tomlab\Downloads\Nagstamon_debug\python36\lib\site-packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)`

**Comment by HenriWahl** [comment]
Maybe https://nagstamon.ifw-dresden.de/how-to-solve-trouble-with-self-signed-certificates/ is of any help?

**Comment by laberator** [comment]
Hi,

I had already checked that option (ignore SSL), so unfortunately it doesn't help in my case.

**Comment by XnS** [comment]
I got the same problem on Linux:

``
DEBUG: 2018-05-17 09:36:31.426439 03_XXXX_NEW FetchURL: http://icinga01.somecompany.dmz/icingaweb2/monitoring/list/hosts?host_state>0&host_state<=2&host_state_type=1&addColumns=host_last_check&format=json CGI Data: None
ERROR: 2018-05-17 09:36:31.427046 03_XXXX_NEW Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Generic.py", line 1370, in FetchURL
    response = self.session.get(url, timeout=self.timeout)
AttributeError: 'NoneType' object has no attribute 'get'
``
The json returned from icingaweb2 is valid.
On a windows client of a colleague it works fine with the same version set.

Nagstamon: 3.0.2
Icingaweb2: icingaweb2-2.5.3-27.1.noarch
Client: Ubuntu 17.10

**Comment by HenriWahl** [comment]
Can you check with latest development binaries of Nagstamon?

**Comment by XnS** [comment]
Hi,
```
ERROR: 2018-06-04 10:13:04.964427 03_FBDN_NEW Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Nagstamon/Servers/Generic.py", line 1373, in FetchURL
    response = self.session.get(url, timeout=self.timeout)
AttributeError: 'NoneType' object has no attribute 'get'
```
v3.1-20180523

**Comment by HenriWahl** [comment]
@XnS are there any special login conditions there on your Icinga2? Apparently Nagstamon does not get a session. :-(

**Comment by HenriWahl** [comment]
I tested now with https://www.icinga.com/demo - works fine for me. How does it for you (credentials are demo:demo)? Just for testing.

**Comment by HenriWahl** [comment]
@laberator This error in your output looks interesting: 
`bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?`
Is there anything Python/lxml-related installed on your system?

**Comment by HenriWahl** [comment]
To everbody else: Does Nagstamon work with ANY monitoring server or just not with IcingaWeb2?

**Comment by XnS** [comment]
@HenriWahl: I got it running on my client now. Initially I just copied the `icinga` profile I used with our old instance and adapted the type to `icingaweb2`. Now I created a new profile and it works.

I cant reproduce it now - sorry for the mess :-/

**Comment by BenoitPoulet** [comment]
@HenriWahl master branch is working with Centreon as server type.

**Comment by laberator** [comment]
@HenriWahl I downloaded 3.0.2 win64 and tried again and I'm happy to report that it works now. I'm not however able to give any information on what's changed, besides the latest creators update from MS and several updates to Icingaweb2 since my initial report.
