### ISSUE TITLE
Version 3.10.0 & 3.10.1 not working on Ubuntu 18.04 

### ISSUE THREAD

**Issue by moerkey** [HenriWahl/Nagstamon#867]
Same as here https://github.com/HenriWahl/Nagstamon/issues/865 but with Ubuntu 18.04.

Nagstamon crashes at start with the following:
Traceback (most recent call last): File "/usr/bin/nagstamon", line 42, in <module> from Nagstamon.QUI import (APP, File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 7031, in <module> dialogs = Dialogs() File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 4403, in __init__ self.settings = Dialog_Settings('settings_main') File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 4795, in __init__ self.signalmapper_colors.mappedString[str].connect(self.color_chooser) AttributeError: 'QSignalMapper' object has no attribute 'mappedString'

**Comment by HenriWahl** [comment]
No idea how you get your error as this should be catched by the changes for 20.04. I get another one:

```
henri@ubuntu1804:~$ nagstamon
[Errno 2] No such file or directory: '/home/henri/.nagstamon/nagstamon.pid'
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 42, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 192, in <module>
    SORT_ORDER = {'descending': 1, 'ascending': 0, 0: Qt.SortOrder.DescendingOrder, 1: Qt.SortOrder.AscendingOrder}
AttributeError: type object 'SortOrder' has no attribute 'DescendingOrder'
```

I see that Ubuntu 18.04 comes with Qt 5.9 which is even more ancient than the version coming with Ubuntu 20.04. This causes the error I get because quite likely some more stuff is not included in the older Qt. So I think the easiest fix will be to upgrade at least to Ubuntu 20.04 which in general is not a bad idea.

**Comment by moerkey** [comment]
I am sorry. You are right. I just copy pasted the error message from the linked issue.

```
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.
Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 42, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 192, in <module>
    SORT_ORDER = {'descending': 1, 'ascending': 0, 0: Qt.SortOrder.DescendingOrder, 1: Qt.SortOrder.AscendingOrder}
AttributeError: type object 'SortOrder' has no attribute 'DescendingOrder'
```

**Comment by HenriWahl** [comment]
> Yeah, I can not tell if it is worth it because 18.04 will be EOL in April 2023.

Yes, this adds to the hassle of finding all pieces of code which have to be made backwards-compatible...

Just one attempt might be a workaround: replace in file `/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py` line 192
```
SORT_ORDER = {'descending': 1, 'ascending': 0, 0: Qt.SortOrder.DescendingOrder, 1: Qt.SortOrder.AscendingOrder}
```
with the old one from version 3.8:
```
SORT_ORDER = {'descending': 1, 'ascending': 0, 0: True, 1: False}
```
Maybe this is enough to make it run.

**Comment by moerkey** [comment]
That doesn't help. After that, you will get a couple of other lines, which have to be updated.
I now have a reason to focus on upgrading to Ubuntu 22.04.
Thank you for your effort.

I would mark this as “won't fix” and update your docs that Ubuntu is supported from 20.04 upwards.
