### ISSUE TITLE
V2: AttributeError: 'NoneType' object has no attribute 'findNext'

### ISSUE THREAD

**Issue by winter1967** [HenriWahl/Nagstamon#227]
I have installed nagstamon2 on a windows7 (32bit) system, then i configured it for icingaweb2 (V2.3.0).

Very curious: I configured my icingaweb2 address and it doesn't load the messages with the error:
AttributeError: 'NoneType' object has no attribute 'findNext'
I restart it, with the same data and it works,
then i try another username, now i've the attibute error.
Changing back to the first username, the same attribute error. Sometimes it works, sometimes not... When it were working without error, i made a copy of the same server settinig:
one of them works, the other have the attribute error.

Sometimes i have with the same settings connection error...

**Comment by HenriWahl** [comment]
Can you provide some debug output by enabling debugging in settings?

**Comment by winter1967** [comment]
Hello Henri,
no problem:

DEBUG: 2016-04-20 09:08:40.012013 Monitor server Created server.
DEBUG: 2016-04-20 09:08:40.277198 Monitor server FetchURL: https://icingaweb2/authentication/login CGI Data: None
DEBUG: 2016-04-20 09:08:40.433189 Monitor server FetchURL: https://nagstamon.ifw-dresden.de/version/unstable CGI Data: None
DEBUG: 2016-04-20 09:08:41.516779 Monitor server FetchURL: https://icingaweb2/about CGI Data: None
ERROR: 2016-04-20 09:08:41.524779 Monitor server Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\IcingaWeb2.py", line 127, in _get_status
  File "C:\Nagstamon\Nagstamon\Servers\IcingaWeb2.py", line 116, in get_server_version
AttributeError: 'NoneType' object has no attribute 'findNext'

DEBUG: 2016-04-20 09:08:44.527779 Monitor server FetchURL: https://icingaweb2/authentication/login CGI Data: None
DEBUG: 2016-04-20 09:08:44.574576 Monitor server FetchURL: https://icingaweb2/about CGI Data: None
ERROR: 2016-04-20 09:08:44.574576 Monitor server Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\IcingaWeb2.py", line 127, in _get_status
  File "C:\Nagstamon\Nagstamon\Servers\IcingaWeb2.py", line 116, in get_server_version
AttributeError: 'NoneType' object has no attribute 'findNext'

ERROR: 2016-04-20 09:09:01.413576 Monitor server Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 137, in _new_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 91, in create_connection
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 81, in create_connection
TimeoutError: [WinError 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 559, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 345, in _make_request
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 784, in _validate_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 217, in connect
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 146, in _new_conn
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04633ED0>: Failed to establish a new connection: [WinError 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 376, in send
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 609, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\retry.py", line 273, in increment
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nagstamon.ifw-dresden.de', port=443): Max retries exceeded with url: /version/unstable (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04633ED0>: Failed to establish a new connection: [WinError 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Generic.py", line 1267, in FetchURL
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 480, in get
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 468, in request
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 576, in send
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 437, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nagstamon.ifw-dresden.de', port=443): Max retries exceeded with url: /version/unstable (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04633ED0>: Failed to establish a new connection: [WinError 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat',))

DEBUG: 2016-04-20 09:09:11.994576 Icingaweb2 Created server.
DEBUG: 2016-04-20 09:09:12.010576 Icingaweb2 FetchURL: https://icingaweb2/authentication/login CGI Data: None
DEBUG: 2016-04-20 09:09:12.079576 Icingaweb2 FetchURL: https://monitor-server/monitor/cgi-bin/about CGI Data: None
ERROR: 2016-04-20 09:09:14.649576 Icingaweb2 Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 137, in _new_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\connection.py", line 67, in create_connection
  File "c:\Python34\lib\socket.py", line 537, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 559, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 345, in _make_request
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 784, in _validate_conn
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 217, in connect
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 146, in _new_conn
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04653C70>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 376, in send
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 609, in urlopen
  File "c:\Python34\lib\site-packages\requests\packages\urllib3\util\retry.py", line 273, in increment
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='monitor-server', port=443): Max retries exceeded with url: /monitor/cgi-bin/about (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04653C70>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Generic.py", line 1240, in FetchURL
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 480, in get
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 468, in request
  File "c:\Python34\lib\site-packages\requests\sessions.py", line 576, in send
  File "c:\Python34\lib\site-packages\requests\adapters.py", line 437, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='monitor-server', port=443): Max retries exceeded with url: /monitor/cgi-bin/about (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04653C70>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

I wonder why nagstmon want to get CGI-Data, in the server settings I said “icingaweb2” …

When I delete the server setting, nagstamon dies, after restart the old server setting still is active .

Then I created new server settings, two server settings were active, after it, I could delete the old server.. But when I have two server settings, I have connection error, after deleting the old server setting (only one server setting active) I have the same error: “AttributeError: 'NoneType' object has no attribute 'findNext'”

Von: Henri Wahl [mailto:notifications@github.com]
Gesendet: Dienstag, 19. April 2016 16:30
An: HenriWahl/Nagstamon
Cc: Winter, Wolfgang
Betreff: Re: [HenriWahl/Nagstamon] V2: AttributeError: 'NoneType' object has no attribute 'findNext' (#227)


Can you provide some debug output by enabling debugging in settings?

**Comment by mj84** [comment]
It appears to me, that i have a similar error, but my Nagstamon won't ever work with Icingaweb2 v2.3.2.
As soon as i authenticate to the configured server, Nagstamon 2.0-beta-20160513 crashes.

Debug log tells me:
DEBUG: 2016-05-13 10:08:17.616794 Monitor server Created server.
DEBUG: 2016-05-13 10:08:17.799608 Monitor server FetchURL: https://icinga.local/icingaweb2/authentication/login CGI Data: None
DEBUG: 2016-05-13 10:08:18.837719 Monitor server FetchURL: https://nagstamon.ifw-dresden.de/version/unstable CGI Data: None
DEBUG: 2016-05-13 10:08:18.991819 Monitor server FetchURL: https://icinga.local/icingaweb2/about CGI Data: None
ERROR: 2016-05-13 10:08:19.014661 Monitor server Traceback (most recent call last):
File "C:\Nagstamon\Nagstamon\Servers\IcingaWeb2.py", line 128, in _get_status
File "C:\Nagstamon\Nagstamon\Servers\IcingaWeb2.py", line 117, in get_server_version
AttributeError: 'NoneType' object has no attribute 'findNext'

**Comment by HenriWahl** [comment]
Most probably fixed with commit https://github.com/HenriWahl/Nagstamon/commit/bdf0c2444e47f5dc42e7bb25276246a3c3661a26 - binaries will be available soon

**Comment by HenriWahl** [comment]
Latest BETA 20160513 binaries available now: https://nagstamon.ifw-dresden.de/nagstamon-20/
