### ISSUE TITLE
Nagstamon and centreon 2.7

### ISSUE THREAD

**Issue by Thiefoumongars** [HenriWahl/Nagstamon#174]
Good day,
After upgrading my centreon to the version 2.7, Nagstamon stopped working.
The issue is linked to some change that centreon made on their website.

They change the location of 1 XML file
-serviceXML.php
old location: /include/monitoring/status/Services/xml/broker/serviceXML.php?
new location: /include/monitoring/status/Services/xml/serviceXML.php?

After changing the line 336 in the file Nagstamon\Nagstamon\Server\centreon.py
from: nagcgiurl_services = self.monitor_cgi_url + "/include/monitoring/status/Services/" + self.XML_NDO + "/serviceXML.php?" + urllib.urlencode({"num":0, "limit":999, "o":"svcpb", "sort_type":"status", "sid":self.SID})
to: nagcgiurl_services = self.monitor_cgi_url + "/include/monitoring/status/Services/xml/serviceXML.php?" + urllib.urlencode({"num":0, "limit":999, "o":"svcpb", "sort_type":"status", "sid":self.SID})
Nagstamon is working with centreon 2.7

I hope this information will help you.

**Comment by dgmorales** [comment]
There is another problem in  2.7 (I'm not sure if I should file another nagstamon issue): 

The o=svcpb parameter must now be statusService=svcpb. With o=svcpb Centreon is returning ALL services, which caused a very noticeable impact on bandwidth usage in our case (server is across a VPN).

Likewise, in hostXML.php they are reading statusHost=hpb instead of o=hpb.

For now, my colleague @fffialho came up with this workaround using mod rewrite on the centreon server:

```
        RewriteEngine On
        RewriteCond %{REQUEST_URI}      /serviceXML.php
        RewriteCond %{QUERY_STRING}     (.*(?:^|&))o=svcpb((?:&|$).*)
        RewriteRule (.*)                $1?%1statusService=svcpb%2 [L]

        RewriteCond %{REQUEST_URI}      /hostXML.php
        RewriteCond %{QUERY_STRING}     (.*(?:^|&))o=hpb((?:&|$).*)
        RewriteRule (.*)                $1?%1statusHost=hpb%2 [L]
```

**Comment by Kiolul** [comment]
Hi Thiefoumongars,

Thx for this workaround. I have the same issue but I don't find centreon.py file on my Windows workstation.
Do you know where the file is stored?
Regards.

**Comment by smeeus** [comment]
@Kiolul 
You can apply the same rewrite logic posted by @dgmorales so you do not have to mess around with code, especially on Windows.

You should have something similar to this in your apache config:

```
	RewriteEngine On

	RewriteCond %{REQUEST_URI}	^(.*)/Services/xml/.*/serviceXML.php$
	RewriteRule ^(.*)$		%1/Services/xml/serviceXML.php [QSA]

	RewriteCond %{REQUEST_URI}	/serviceXML.php
	RewriteCond %{QUERY_STRING}	(.*(?:^|&))o=svcpb((?:&|$).*)
	RewriteRule ^(.*)$		$1?%1statusService=svcpb%2 [L]

	RewriteCond %{REQUEST_URI}	/hostXML.php
	RewriteCond %{QUERY_STRING}	(.*(?:^|&))o=hpb((?:&|$).*)
	RewriteRule ^(.*)$		$1?%1statusHost=hpb%2 [L]
```


It still gives me problems though, I can't get any problems and/or data to list. I have the following from the debug logging:

```
DEBUG: 2016-01-25 12:05:33.020399 hostname   Refreshing output - server is already checking: False
DEBUG: 2016-01-25 12:06:34.088078 hostname   FetchURL: https://hostname.domain.tld/centreon/include/monitoring/status/Hosts/xml/broker/hostXML.php?sort_type=status&num=0&limit=999&o=hpb&sid=asessionidstring CGI Data: None
DEBUG: 2016-01-25 12:06:34.256547 hostname   FetchURL: https://hostname.domain.tld/centreon/include/monitoring/status/Services/xml/broker/serviceXML.php?sort_type=status&num=0&limit=999&o=svcpb&sid=asessionidstring CGI Data: None
DEBUG: 2016-01-25 12:06:34.413464 hostname   server return values:  
```

I'll give the code a quick view to see if there's an easy workaround for it. If not...

**Comment by pmarconnier** [comment]
Hi everyone,

As I am, like Kiolul, on Windows, I'd like to modify my apache configuration.
But my several tries to modify my /etc/httpd/conf/httpd.conf, or the /etc/httpd/conf.d/10-centreon.conf (and some other conf files) are all unsuccessed.

I'm sure I'm missing something, so could you please clarify where to put these RewriteConds ?

Thanks & regards,

**Comment by dgmorales** [comment]
@pmarconnier We have them in /etc/httpd/conf.d/10-centreon.conf, inside the <Directory "/usr/share/centreon/www">.

**Comment by Kiolul** [comment]
Hello Guys,

Thx dgmorales, I just tried your solution and it works great.

**Comment by pmarconnier** [comment]
Merci beaucoup @dgmorales !
Actually, I had alreay tried but I got a 403 forbidden error message.

So I've looked in my ssl_error.log and have seen the "Options FollowSymLinks or SymLinksIfOwnerMatch is off" message.

I've also modified the 10-centreon.conf with :+1: 
> Options Indexes FollowSymLinks

and now It's perfectly OK !

**Comment by mmmanes** [comment]
Hello,

after applying rewrite mod etc. I am free of error messages, but can not see anything - not even menu bar of the Centreon 2.7.1 ... Could please someone post working 10-centreon.conf?

Many thanks

**Comment by pmarconnier** [comment]
```
Alias /centreon /usr/share/centreon/www/

<Directory "/usr/share/centreon/www">
	Options Indexes FollowSymLinks
	AllowOverride AuthConfig Options
	Order allow,deny
	Allow from all

	RewriteEngine On

	RewriteCond %{REQUEST_URI}  ^(.*)/Services/xml/.*/serviceXML.php$
	RewriteRule ^(.*)$      %1/Services/xml/serviceXML.php [QSA]

	RewriteCond %{REQUEST_URI}  /serviceXML.php
	RewriteCond %{QUERY_STRING} (.*(?:^|&))o=svcpb((?:&|$).*)
	RewriteRule ^(.*)$      $1?%1statusService=svcpb%2 [L]

	RewriteCond %{REQUEST_URI}  /hostXML.php
	RewriteCond %{QUERY_STRING} (.*(?:^|&))o=hpb((?:&|$).*)
	RewriteRule ^(.*)$      $1?%1statusHost=hpb%2 [L]

	RewriteCond %{REQUEST_URI}      /index.php
	RewriteCond %{QUERY_STRING}     (.*(?:^|&))p=101((?:&|$).*)
	RewriteRule ^(.*)$              $1?%1p=1%2 [L]

</Directory>

```

**Comment by mmmanes** [comment]
@pmarconnier Many thanks, no change ... my Monitor URL is http://IPaddress/centreon , type Centreon... probably something on my side, thanks again

**Comment by smeeus** [comment]
I tend to put my rewrite rules in a `<Location>` block rather then the `<Directory>` block. I guess it makes things cleaner and more logical to follow for me personally.

My 10-centreon.conf looks like this

```
Alias /centreon /usr/share/centreon/www/
<Directory "/usr/share/centreon/www">
        Options Indexes
        AllowOverride AuthConfig Options
	Order Deny,Allow
	Deny from All
	AuthType Basic
	more authentication stuff...
	Allow from ...
	Satisfy any
</Directory>

<Location /centreon>
	#RedirectMatch ^/$ /centreon/index.php

	Options FollowSymLinks

	# Centreon 2.7.x NagstaMon fixes
	################################

	RewriteEngine On

	RewriteCond %{REQUEST_URI}	^(.*)/Services/xml/.*/serviceXML.php$
	RewriteRule ^(.*)$		%1/Services/xml/serviceXML.php [QSA]

	RewriteCond %{REQUEST_URI}	/serviceXML.php
	RewriteCond %{QUERY_STRING}	(.*(?:^|&))o=svcpb((?:&|$).*)
	RewriteRule ^(.*)$		$1?%1statusService=svcpb%2 [L]

	RewriteCond %{REQUEST_URI}	/hostXML.php
	RewriteCond %{QUERY_STRING}	(.*(?:^|&))o=hpb((?:&|$).*)
	RewriteRule ^(.*)$		$1?%1statusHost=hpb%2 [L]

	RewriteCond %{REQUEST_URI}	/index.php
	RewriteCond %{QUERY_STRING}	(.*(?:^|&))p=101((?:&|$).*)
	RewriteRule ^(.*)$		$1?%1p=1%2 [L]

</Location>
```

Other things you may have to check:
- Make sure that you use the autologin feature as mentioned in issues #165 and #168 .
- Fiddle with the `Options` statements to get rid off potential 403 errors in your setup.
- Make sure that if you use ACL's in any way for a non admin user with autologin, the ACL's actually work. Login in with the non admin user via the web interface and check that you can actually see what you need to see.
- Try to open the returned XML urls from your request log in your browser. There should be data in them.

**Comment by pmarconnier** [comment]
Then, on my side, I'm still on Nagstamon 1.0.1 version.
I've tried Nagstamon 2.0 but it didn't work.

**Comment by fizze** [comment]
Same here. I'm using Centreon 2.7.1 on CES, with the httpd config from above.
The log file is empty, so I can't check any XML urls.
Using a privileged user in Centreon does not make a difference.

In NagStaMon 1.0.1 I get no errors. In 2.0 I get "cannot insert null into tag"...?

**Comment by HenriWahl** [comment]
The fixes for Centreon are not yet in 2.0. Soon to come there...

**Comment by Lca94** [comment]
I found the good result for Nagtammon for Windows :
Nagstamon search on Services/xml/broker/
CentreonWeb 2.7 have only the files on Services/ 

(see at top level on #174 -serviceXML.php old location: /include/monitoring/status/Services/xml/broker/serviceXML.php?
new location: /include/monitoring/status/Services/xml/serviceXML.php?
...)

To solve the problem without recompiling Windows , you create the " broker " directory with the corrected files .

Soluce => Copying Services files / Adding "../" on the path of require_once centreon.config.php on all new files / now its ok.
Do a autologin server on Seting on Nagstammon => "Login / Password" is not working.

this is just a temporary solution because we changed / add files.

Here, see the differential on source xml versus new files on "broker" directory :
(Just "../" 6 times vs 7 times on broker files)
---

$ cd /include/monitoring/status/Services/xml
$ find -maxdepth 1 -name "*.php" -exec diff {} broker/{} \;
39c39,42
< require_once realpath(dirname(__FILE__) . "/../../../../../../config/centreon.config.php");
---
> #
> # correction = debug nagstamon  issue 174 on CentreonWeb 2.7 = ( cd /include/monitoring/status/; mkdir Services/xml/brorker; cp Services/xml/*.php; chown -R centreon: Services/xml/broker; sed -i 's:"/../../../../../../config/centreon.config.php":"/../../../../../../../config/centreon.config.php":g'; cd Services/xml; find -maxdepth 1 -name "*.php" -exec diff {} broker/{} \; )
> require_once realpath(dirname(__FILE__) . "/../../../../../../../config/centreon.config.php");
> #
41c41
<       require_once realpath(dirname(__FILE__) . "/../../../../../../config/centreon.config.php");
---
>       require_once realpath(dirname(__FILE__) . "/../../../../../../../config/centreon.config.php");
41c41
<       require_once realpath(dirname(__FILE__) . "/../../../../../../config/centreon.config.php");
---
>       require_once realpath(dirname(__FILE__) . "/../../../../../../../config/centreon.config.php");
41c41
< require_once realpath(dirname(__FILE__) . "/../../../../../../config/centreon.config.php");
---
> require_once realpath(dirname(__FILE__) . "/../../../../../../../config/centreon.config.php");
39c39
< require_once realpath(dirname(__FILE__) . "/../../../../../../config/centreon.config.php");
---
> require_once realpath(dirname(__FILE__) . "/../../../../../../../config/centreon.config.php");

----

May be, somebody could explain to me why deleting the "broker" directory on "Services" but not in the other directories "monitoring" (cf. /include/monitoring/status/) as Common, Hosts, Scheduling, ServicesHostGroups, TopCounter, HostGroups, Meta, Notifications, or ServicesServiceGroups ??

If Yes, thank you in advance :)

**Comment by selfcracker** [comment]
Hello,

do you get any delay considering this problem, soon but ?
upgraded to 2.7 and unable to use nagstamon 2.0.

**Comment by fizze** [comment]
I don't understand LCA94's comment - is he talking about changes in NagStaMon or in Centreon-Web?
Has anyone gotten in touch with the Centreon-Web developers yet?
I'd really like to help fixing this issue.

**Comment by HenriWahl** [comment]
There is already something done in https://github.com/benoiteolas/Nagstamon - I think this will soon result in a pull request.

**Comment by fizze** [comment]
I tried the beta from yesterday, still no dice.

Here are the relevant lines from the log:
`DEBUG: 2016-05-12 10:25:38.696161 centreon FetchURL: https://centreon.domain.local:8443/centreon/index.php CGI Data: {'submit': 'Login', 'password': 'password', 'useralias': 'username'}
DEBUG: 2016-05-12 10:25:39.824661 centreon FetchURL: https://centreon.domain.local:8443/centreonmain.php CGI Data: {'sid': 'kvau4tf401ahf72gd556ek97m3', 'p': 201}
DEBUG: 2016-05-12 10:25:39.851161 centreon FetchURL: https://centreon.domain.local:8443/centreon/include/monitoring/status/Hosts/xml/broker/hostXML.php?num=0&o=hpb&sort_type=status&limit=9999&sid=kvau4tf401ahf72gd556ek97m3 CGI Data: None
DEBUG: 2016-05-12 10:25:39.914161 centreon FetchURL: https://centreon.domain.local:8443/centreon/include/monitoring/status/Services/xml/broker/serviceXML.php?num=0&o=svcpb&sort_type=status&limit=9999&sid=kvau4tf401ahf72gd556ek97m3 CGI Data: None
DEBUG: 2016-05-12 10:25:39.980661 centreon FetchURL: https://centreon.domain.local:8443/centreon/include/monitoring/status/Services/xml/broker/serviceXML.php?num=0&o=meta&sort_type=status&limit=9999&sid=kvau4tf401ahf72gd556ek97m3 CGI Data: None
ERROR: 2016-05-12 10:25:40.046661 centreon Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Centreon.py", line 454, in _get_status
  File "c:\Python34\lib\site-packages\bs4\element.py", line 366, in append
  File "c:\Python34\lib\site-packages\bs4\element.py", line 300, in insert
ValueError: Cannot insert None into a tag.`

**Comment by HenriWahl** [comment]
Please check the latest 20160519 binaires from https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by vgaudin** [comment]
unable to log using nagstamon on a 2.7.4 using credential or autologin

here is the debug file : 
DEBUG: 2016-05-19 14:20:31.031525 CentreonSupervision FetchURL: http://centreon.cpr.sncf.fr/include/monitoring/status/Hosts/xml/hostXML.php?num=0&o=hpb&limit=999&sort_type=status&sid=ERROR CGI Data: None
DEBUG: 2016-05-19 14:20:31.067745 CentreonSupervision FetchURL: http://centreon.cpr.sncf.fr/include/monitoring/status/Services/xml/serviceXML.php?num=0&o=svcpb&limit=999&sort_type=status&sid=ERROR CGI Data: None
DEBUG: 2016-05-19 14:20:31.102958 CentreonSupervision FetchURL: http://centreon.cpr.sncf.fr/include/monitoring/status/Meta/xml/metaServiceXML.php?num=0&o=meta&limit=999&sort_type=status&sid=ERROR CGI Data: None
ERROR: 2016-05-19 14:20:31.110001 CentreonSupervision Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Centreon.py", line 521, in _get_status
  File "c:\Python34\lib\site-packages\bs4\element.py", line 366, in append
  File "c:\Python34\lib\site-packages\bs4\element.py", line 300, in insert
ValueError: Cannot insert None into a tag.

DEBUG: 2016-05-19 14:20:32.661407 CentreonSupervision FetchURL: http://centreon.cpr.sncf.fr/index.php?p=101&autologin=1&useralias=username&token=U1UpHQPXu CGI Data: None
DEBUG: 2016-05-19 14:20:32.665432 CentreonSupervision Autologin : username : U1UpHQPXu
ERROR: 2016-05-19 14:20:32.666438 CentreonSupervision Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Centreon.py", line 189, in _get_sid
  File "c:\Python34\lib\site-packages\requests\cookies.py", line 287, in __getitem__
  File "c:\Python34\lib\site-packages\requests\cookies.py", line 345, in _find_no_duplicates
KeyError: "name='PHPSESSID', domain=None, path=None"

DEBUG: 2016-05-19 14:20:33.123207 CentreonSupervision FetchURL: http://centreon.cpr.sncf.fr/index.php?p=101&autologin=1&useralias=username&token=U1UpHQPXu CGI Data: None
DEBUG: 2016-05-19 14:20:33.126226 CentreonSupervision Autologin : username : U1UpHQPXu
ERROR: 2016-05-19 14:20:33.127232 CentreonSupervision Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Centreon.py", line 189, in _get_sid
  File "c:\Python34\lib\site-packages\requests\cookies.py", line 287, in __getitem__
  File "c:\Python34\lib\site-packages\requests\cookies.py", line 345, in _find_no_duplicates
KeyError: "name='PHPSESSID', domain=None, path=None"

DEBUG: 2016-05-19 14:20:33.127232 CentreonSupervision FetchURL: http://centreon.cpr.sncf.fr/include/monitoring/status/Hosts/xml/hostXML.php?num=0&o=hpb&limit=999&sort_type=status&sid=ERROR CGI Data: None
DEBUG: 2016-05-19 14:20:33.132262 CentreonSupervision FetchURL: http://centreon.cpr.sncf.fr/include/monitoring/status/Services/xml/serviceXML.php?num=0&o=svcpb&limit=999&sort_type=status&sid=ERROR CGI Data: None
DEBUG: 2016-05-19 14:20:33.136287 CentreonSupervision FetchURL: http://centreon.cpr.sncf.fr/include/monitoring/status/Meta/xml/metaServiceXML.php?num=0&o=meta&limit=999&sort_type=status&sid=ERROR CGI Data: None
ERROR: 2016-05-19 14:20:33.140311 CentreonSupervision Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Centreon.py", line 521, in _get_status
  File "c:\Python34\lib\site-packages\bs4\element.py", line 366, in append
  File "c:\Python34\lib\site-packages\bs4\element.py", line 300, in insert
ValueError: Cannot insert None into a tag.

**Comment by HenriWahl** [comment]
@benoiteolas any idea?

**Comment by lorrainezo** [comment]
Hello,

Version 20160519 works with Centreon 2.7.3 with autologin.
But like precedents versions, if you put a bad autologin key nagstamon return only a OK in green.

Thanks for your job

**Comment by benoiteolas** [comment]
indeed, their is no check who validate conf.
I think we must enhanced this. 
I did this version in hurry to get it added to Nagstamon 2.0, i will try to get it better with more validity checks.

**Comment by fizze** [comment]
It works with username/password with my Centreon 2.7.4 just fine! Thanks for fixing that!

The downside is that it odes not work with Centreon 2.6.1 with username/password. Same config works fine in the old nagstamon....

I get this in the log

`DEBUG: 2016-05-20 09:12:04.185796 centreon-server FetchURL: https://centreon-server.domain.local/centreon/index.php CGI Data: None
DEBUG: 2016-05-20 09:12:05.679796 centreon-server Centreon version detected : 2.[3-6]
DEBUG: 2016-05-20 09:12:05.679796 centreon-server FetchURL: https://centreon-server.domain.local/centreon/index.php CGI Data: None

ERROR: 2016-05-20 09:12:06.267796 centreon-server Traceback (most recent call last):
  File "C:\Nagstamon\Nagstamon\Servers\Centreon.py", line 180, in _get_sid
TypeError: 'NoneType' object is not subscriptable

DEBUG: 2016-05-20 09:12:06.267796 centreon-server FetchURL: https://centreon-server.domain.local/centreon/main.php CGI Data: {'sid': 'ERROR', 'p': 201}
DEBUG: 2016-05-20 09:12:07.427796 centreon-server Could not detect the broker for Centeron 2.[3-6]. Using Centreon Broker
DEBUG: 2016-05-20 09:12:07.427796 centreon-server FetchURL: https://centreon-server.domain.local/centreon/include/monitoring/status/Hosts/xml/broker/hostXML.php?sid=ERROR&num=0&o=hpb&limit=999&sort_type=status CGI Data: None
DEBUG: 2016-05-20 09:12:08.026796 centreon-server FetchURL: https://centreon-server.domain.local/centreon/include/monitoring/status/Services/xml/broker/serviceXML.php?sid=ERROR&num=0&o=svcpb&limit=999&sort_type=status CGI Data: None
DEBUG: 2016-05-20 09:12:08.622796 centreon-server FetchURL: https://centreon-server.domain.local/centreon/include/monitoring/status/Meta/xml/broker/metaServiceXML.php?sid=ERROR&num=0&o=meta&limit=999&sort_type=status CGI Data: None
`

**Comment by lorrainezo** [comment]
Hello,
A litlle bug found in v20160519 : if you don't check "Save password" when you use autologin, you have pop up 'Authenticate' of my define server each time you start Nagstamon.

**Comment by benoiteolas** [comment]
Centreon 2.6.1 is pretty old and is full of security holes.
I will try to add support for it but with no warranty and for that i need to rebuild a server with this specific release...

The bug for the Auth dialog is a know bug.

I will have a look for « 'CentreonServer' object has no attribute 'conf'.» but i'm using it all the day long and didn't have it yet.

**Comment by fizze** [comment]
Correct, as soon as NagStaMon works stable with Centreon 2.7.x I'll update this installation. It seems we're almost there.

**Comment by HenriWahl** [comment]
ba75672008fcbab947b338fa4714a68e1380d58a tries to avoid useless authentication dialog.

**Comment by benoiteolas** [comment]
authentication dialog bug fixed.

**Comment by HenriWahl** [comment]
Please check latest 20160527 binaries from https://nagstamon.ifw-dresden.de/nagstamon-20/ which address the not-noticing-any-auth-problems problem.

**Comment by HenriWahl** [comment]
Does this work now for all of you? If so, I would like to close this issue to come closer to a 2.0 release.

**Comment by mmmanes** [comment]
For me it's OK now, it works with Centreon 2.7.1 and 2.7.2.

Many thanks

With Best Regards
Zdenek Jerman

2016-05-31 17:28 GMT+02:00 Henri Wahl <notifications@github.com>:

**Comment by vgaudin** [comment]
it's now oky for me  using centreon 2.7.4, the message error is now more detailed ..

many thanks.
vincent

**Comment by lorrainezo** [comment]
Hello,

I come back after 2 weeks of holidays, so i haven't investigated since.
Concerning bug of pop up 'Authenticate' with autologin, it's resolved in v20160601-win64
Concerning bug after some hours of utilization, my collegue have same problem. 
I have installed v20160601-win64 instead of use .zip, because with v1.01 we have always used setup version....
Also there are checkbox which can may be resolve our problem : 
* in Settings > Servers > in bottom of window : use system keyring for server credentials
* in Settings > Servers > Edit server > Authentication : Basic/Digest ; and Timeout.

benoiteolas, can you say me wich options you have selected for these 2 settings ?

Regards

**Comment by benoiteolas** [comment]
Hello,
in Settings > Servers > in bottom of window : use system keyring for server credentials
-> unchecked for me, as i'm using a key for autologin

in Settings > Servers > Edit server > Authentication : Basic/Digest ; and Timeout.
-> Authentification : Basic; Timeout : 10

If you are loosing the auth after some hours, it sound like it's related to the use of «system keyring for server credentials».

I don't know what is this option and how it's used.

**Comment by HenriWahl** [comment]
The option "system keyring for server credentials" allows to store username/password not in config file but in system key storage - named differently on all major OS, but works the same.

As far as I remember the login key ist not stored there. Even if it would this should have no consequences for the session timeout problem.

Some years ago I added the Hook() in servers which was mainly used from Centreon to renew the session. Somewhen I removed it, assuming it was not needed anymore due to login key. Some days ago I saw that it was brought back by @benoiteolas with https://github.com/HenriWahl/Nagstamon/commit/9e06728b326d6c317425b551c8d6170a37c35dd3 so I thought it will be still needed and working.

**Comment by lorrainezo** [comment]
This modification 9e06728 is dated from 15 Apr.
Do you know, when it's was compiled ?

Also, i remark than after EDIT menu upper on actives Warning, there only Connected displayed (replaced by Refreshed when nagstamon refresh Warning).
In version 1.01, there is also date time about last check/refresh.
Is that it wanted to delete this information ?

**Comment by HenriWahl** [comment]
No, I do not remember a compile date but it must be the next testing release after that date.

The info about last check/refresh I simply forgot to implement - good point!

**Comment by HenriWahl** [comment]
Hm... funny... Hook() is never called... I fear I have to check what I actually did in the 1.0 version.

**Comment by lorrainezo** [comment]
Hello,

After 2 days of use in with setup version v20160601-win64 there is no more "AttributeError : 'CentreonServer' object has no attribute 'conf'."  On my pc and same for my collegue.

I suppose than zip version can't read/write access to some folder on computer.... or version v20160601-win64 has corrected problem from v20160519-win64....

**Comment by HenriWahl** [comment]
Strange... the source for zip/exe is the same. I assume the second solution being the correct interpretation.

**Comment by HenriWahl** [comment]
@lorrainezo So with the 20160601 you also had no timeout trouble?

**Comment by lorrainezo** [comment]
Yes no more problem with v20160601-win64-setup on win8.1 64bit

**Comment by benoiteolas** [comment]
Hello,

I will be of vacation for 4 weeks, far from Github.

Are all the bugs solved ?

**Comment by lorrainezo** [comment]
Hello,

For me, timeout problem seem resolved.

Have a nice holidays

**Comment by HenriWahl** [comment]
No more comments, assuming to be fixed.
