### ISSUE TITLE
Version 3.10.0 not working on Kubuntu 20.04

### ISSUE THREAD

**Issue by jvidals** [HenriWahl/Nagstamon#865]
Kubuntu 20.04

Nagstamon crashes at start with the following:
`Traceback (most recent call last):
  File "/usr/bin/nagstamon", line 42, in <module>
    from Nagstamon.QUI import (APP,
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 7031, in <module>
    dialogs = Dialogs()
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 4403, in __init__
    self.settings = Dialog_Settings('settings_main')
  File "/usr/lib/python3/dist-packages/Nagstamon/QUI/__init__.py", line 4795, in __init__
    self.signalmapper_colors.mappedString[str].connect(self.color_chooser)
AttributeError: 'QSignalMapper' object has no attribute 'mappedString'`

**Comment by HenriWahl** [comment]
Did any previous version run? Tested with Ubuntu 20.04 with no problem :-(

**Comment by jvidals** [comment]
Yes,

I had the previous stable version running without issue. I will do a full
reboot and try again when I can afford the downtime.

**Comment by esemate** [comment]
Also it's happening to me, I've rebooted and still happening

**Comment by HenriWahl** [comment]
I apparently used a newer Qt5 version - the one that comes with Ubuntu 20.04 is 5.12 and I used 5.15 which has some more futureproof methods. I am about to check this out.

**Comment by HenriWahl** [comment]
One pretty surely working solution is upgrading Ubuntu to 22.04.

**Comment by HenriWahl** [comment]
Please checkout the latest testing version at https://github.com/HenriWahl/Nagstamon/releases/tag/latest where this issue is addressed.

**Comment by esemate** [comment]
Working! Thank you!!

**Comment by jvidals** [comment]
The latest testing version works for me as well. Thanks!
