### ISSUE TITLE
Nagstamon 2.0 no working with Centreon 2.6.5

### ISSUE THREAD

**Issue by lorenzo8769** [HenriWahl/Nagstamon#165]
Hi, 

I'm use Centreon 2.6.5 with last Broker/Engine, and with it, nagstamon 2.0 no work.

OS = Win10 64bit

Have you got a solution ?

Thx

Laurent

**Comment by HenriWahl** [comment]
Did it work with Nagstamon 1.0.1? Or even older versions?

**Comment by lorenzo8769** [comment]
ERROR msg:
ERROR: 2015-10-26 11:59:41.177014 centreon-225 Traceback (most recent call last):
  File "c:\Users\Henri Wahl\Seafile\Nagstamon-Qt-Python3\Nagstamon\Nagstamon\Servers\Centreon.py", line 454, in _get_status
  File "C:\Python34\lib\site-packages\bs4\element.py", line 362, in append
  File "C:\Python34\lib\site-packages\bs4\element.py", line 317, in insert
AttributeError: 'NoneType' object has no attribute 'parent'


And no work with Nagstamon 1.0.1

**Comment by HenriWahl** [comment]
OK so this looks like a version-independent problem. I am now focused on the GUI port for version 2.0 thus I can look after this Centreon problem later.

**Comment by LeDistordu** [comment]
Since 2.6.5 with last engine, for my nagstamon all is always ok... I have three criticals but all is ok

**Comment by lorenzo8769** [comment]
Nagstamon 1.0.1 with centreon 2.6.1 / Windows 7 = OK
Nagstamon 1.0.1 with centreon 2.6.5 / Windows 7 = NOK
Nagstamon 1.0.1 with centreon 2.6.1 + 2.6.5 / Windows 10 64bits = NO RUN
Nagstamon 2.0 27102015 with centreon 2.6.1 / Windows7 = OK
Nagstamon 2.0 27102015 with centreon 2.6.5 / Windows7 = NOK
Nagstamon 2.0 27102015 with centreon 2.6.1 + 2.6.5 / Windows 10 64bits = RUN but NOK

**Comment by HenriWahl** [comment]
So it looks like Centreon 2.6.5 related. Would be interesting what they changed or if you configured them differently.

**Comment by lorenzo8769** [comment]
What do you need ?

**Comment by HenriWahl** [comment]
@lorenzo8769  As above - do you know of any changes coming with Centreon 2.6.5 or did you change some setup? Maybe connect to @LeDistordu who seems to have a working setup.

**Comment by lorenzo8769** [comment]
I did the update "yum update centreon- *" on CentOS CES. The nagstamon configuration has not changed.

**Comment by lorenzo8769** [comment]
Error msg in nagstamon 2.0 with centreon 2.6.5:
AttributeError: 'NoneType' object has no attribute 'parent'

**Comment by nmatexo** [comment]
Hi,

It looks like there is a similar problem with Centreon 2.6.6 and Nagstamon 1.0.1 / 2.0-alpha-20151029 (tested both versions) running on Win 7 / Ubuntu 14.04 (tested both too)

Nagstamon reports it as "OK" whereas there are clearly some warnings / criticals alerts

**Comment by nmatexo** [comment]
update : to get rid of the "always OK" problem since (at least) 2.6.6, it seems we have to use the "Use autologin" feature (and thus, we have to generate a key on the centreon server).

Successfully tested on nagstamon 1.0.1 / Ubuntu 14.04

**Comment by Michel78** [comment]
Hi All,

I have the same problem and autologon is not working any more. 

Nagstamon reports it as "OK" whereas there are clearly some warnings / criticals alerts

Does someone know how to fix this ?

Specs

Centos 6.7
nagstamon 1.0.1
Centreon 2.6.6

Thanks


Michel

**Comment by lorenzo8769** [comment]
Hi @HenriWahl 

Do you have a solution for us

Best Regard,
Laurent

**Comment by HenriWahl** [comment]
Nothing changed.... :-(

**Comment by lorrainezo** [comment]
Hello,

I have same problem with nagstamon 1.0.1 and Centreon 2.6.6.
Problem was resolved with autologin feature (enable autologin feature in Centreon, next generate autologin Key in your account and last paste this autologin Key in Server Setting in Nagstatmon)

I think there is a bug in nagstamon with all versions of Centreon : if you put a bad login/password, nagstamon report as OK in green (confirmed with nagstamon 1.0.1 and Centreon 2.6.1).

**Comment by lorenzo8769** [comment]
Great, it's OK for me !!!

Thx @lorrainezo

**Comment by florian-asche** [comment]
Hi, there is Centreon 2.7.0 out now. There are some major changes to the webinterface.
I tested the Nagstatmon, that is out today, and its not working again.

**Comment by HenriWahl** [comment]
Please see https://github.com/HenriWahl/Nagstamon/issues/172

**Comment by florian-asche** [comment]
Hello all! 

I think since Centreon 2.6.5 is old, not the newst version we can close this issue and concentrate on #174 

[y|n]?

**Comment by HenriWahl** [comment]
Please check the latest 20160519 binaires from https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by lorrainezo** [comment]
Hello,

Version 20160519  works with Centreon 2.7.3 with autologin.
But like precedents versions, if you put a bad autologin key nagstamon return only a OK in green.

Thanks for your job

**Comment by florian-asche** [comment]
Hi @HenriWahl i downloaded the version you mentioned, and its working great with Centreon 2.7.4 and Login via Username + Password. Username and Autologin Key is working too.

GREAT WORK!

**Comment by HenriWahl** [comment]
Enough other Centreon issues open so this one might be closed safely.
