### ISSUE TITLE
Fails to build on Python 3.8: AttributeError: module 'platform' has no attribute 'dist'

### ISSUE THREAD

**Issue by moschlar** [HenriWahl/Nagstamon#616]
Python 3.8:
```
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    DIST, DIST_VERSION, DIST_NAME = platform.dist()
AttributeError: module 'platform' has no attribute 'dist'
```

Python 3.7:
```
setup.py:36: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  DIST, DIST_VERSION, DIST_NAME = platform.dist()
```

**Comment by moschlar** [comment]
For the Debian package, I have now added a patch to just remove the whole version string shenanigans... Is it really necessary?

**Comment by HenriWahl** [comment]
True, this module is removed in Python 8. I think your patch is OK as version checking makes no sense on Debian anyway.

**Comment by HenriWahl** [comment]
How exactly does the patch look like?

**Comment by HenriWahl** [comment]
platform.dist() is only needed for building. I suppose it should be replaced with the distro module, because the distribution information is relevant.

**Comment by HenriWahl** [comment]
Fixed it by replacing platform.dist() for Linux by https://github.com/HenriWahl/Nagstamon/commit/18da65904fb79d1560f3d9a0aef6594600ac2c9f

Shall be working in a future 3.4.x-release out of the box for you.

If *BSD will need this information is to be seen.

**Comment by moschlar** [comment]
Sorry for testing so late:
```
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    DIST, DIST_VERSION, DIST_NAME = get_distro()
  File "/build/nagstamon-3.4.1/Nagstamon/Helpers.py", line 457, in get_distro
    return (os_release_dict['ID'], os_release_dict['VERSION_ID'], os_release_dict['NAME'])
KeyError: 'VERSION_ID'
```
Because `/etc/os-release` on Debian testing/unstable is:
```
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by HenriWahl** [comment]
Please check either with latest 3.4.x or master branch - maybe can be patched into current package because at the moment there is no soon 3.4.2 in sight?
